function checkOK(result, fieldName)
  if (result ~= "OK") then
    print(tostring(result).." for field: "..fieldName)
  end
end

function writeMADescs()
  local handleMA=structmsg2.createDispatcher();
  result=structmsg2.openFile(handleMA,"DescMA.txt","w")
  checkOK(result,"open")  
  result=structmsg2.writeLine(handleMA, "#,18\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA, "@dst,uint16_t,2\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"@src,uint16_t,2\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"@totalLgth,uint16_t,2\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"@cmdKey,uint8_t,1\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"MACAddr,uint8_t*,6\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"IPAddr,uint8_t*,4\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"FirmVers,uint8_t*,6\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"SerieNum,uint8_t*,4\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"rssi,uint8_t,1\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"ModConn,uint8_t,1\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"DevMode,uint8_t,1\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"DevSec,uint8_t,1\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"ErrMain,uint8_t,1\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"ErrSub,uint8_t,1\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"date,uint8_t*,6\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"numSsid,uint8_t,1\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"Reserve,uint8_t*,3\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"@crc,uint8_t,1\n")
  checkOK(result,"write")    
  result=structmsg2.closeFile(handleMA)
  checkOK(result,"close") 
end

McuPart=tonumber("4D00",16)
WifiPart=tonumber("5700",16)

function writeMAVals()
  local handleMA=structmsg2.createDispatcher();
  result=structmsg2.openFile(handleMA,"ValMA.txt","w")
  checkOK(result,"open")  
  result=structmsg2.writeLine(handleMA, "#,15\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA, "@dst,"..McuPart.."\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"@src,"..WifiPart.."\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"MACAddr,@getMACAddr\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"IPAddr,@getIPAddr\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"FirmVers,@getFirmwareVersion\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"SerieNum,@getSerieNumber\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"rssi,@getRSSI\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"ModConn,@getModuleConnection\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"DevMode,@getDeviceMode\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"DevSec,@getDeviceSecurity\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"ErrMain,@getErrorMain\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"ErrSub,@getErrorSub\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"date,@getDateAndTime\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"numSsid,@getSSIDs\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA,"Reserve,@getReserve3\n")
  checkOK(result,"write")    
  result=structmsg2.closeFile(handleMA)
  checkOK(result,"close") 
end

writeMADescs()
writeMAVals()
print("done")
