function checkOK(result, fieldName)
  if (result ~= "OK") then
    print(tostring(result).." for field: "..fieldName)
  end
end

function writeMsgActions()
  local handleMA=structmsg2.createDispatcher();
  result=structmsg2.openFile(handleMA,"MsgActions.txt","w")
  checkOK(result,"open")  
  result=structmsg2.writeLine(handleMA, "#,17\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA, "runClientMode,1,uint8_t,B\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA, "runAPMode,2,uint8_t,B\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA, "runLightSleepWakeupMode,3,uint8_t,B\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA, "runLightSleepNoWakeupMode,4,uint8_t,B\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA, "runWpsMode,5,uint8_t,B\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA, "runTestMode,"..tonumber("D0",16)..",uint8_t,B\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA, "runDeletePasswdCMode,"..tonumber("E0",16)..",uint8_t,B\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA, "getMacAddr,2,uint8_t,M\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA, "getFirmeareVersion,2,uint8_t,M\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA, "getSerieNumber,2,uint8_t,M\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA, "getRSSI,2,uint8_t,M\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA, "getModuleConnection,2,uint8_t,M\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA, "getDeviceMode,2,uint8_t,M\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA, "getErrorMain,2,uint8_t,M\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA, "getErrorSub,2,uint8_t,M\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA, "getDateAndTime,2,uint8_t,M\n")
  checkOK(result,"write")    
  result=structmsg2.writeLine(handleMA, "getSSIDs,2,uint8_t,M\n")
  checkOK(result,"write")    
  result=structmsg2.closeFile(handleMA)
  checkOK(result,"close") 
end

writeMsgActions()
print("done")
